version: '3'
services:

  configserver:
    ports:
      - "8888:8888"

  eurekaserver:
    ports:
      - "8761:8761"

  database:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB:       "jsource"