version: '3'
services:
  configserver:
    ports:
      - "8888:8888"
    container_name: configserver-dev
    environment:
      SERVER_PORT: 8888
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/VadOs1/jsource/"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS: "config-repo/auth-service"

  eurekaserver:
    ports:
      - "8761:8761"
    container_name: eurekaserver-dev
    environment:
      SERVER_PORT: 8761
      EUREKA_INSTANCE_HOSTNAME: "localhost"
      EUREKA_CLIENT_REGISTERWITHEUREKA: "false"
      EUREKA_CLIENT_FETCHREGISTRY: "false"
      EUREKA_SERVER_WAITTIMEINMSWHENSYNCEMPTY: 0
      EUREKA_SERVICEURL_DEFAULT_ZONE: "http://localhost:8761/eureka"

  database:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB:       "jsource"
    container_name: postgres-dev
