server:
  port: 8761

eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
