server:
  port: 8761

eureka:
  instance:
    preferIpAddress: false
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
