server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/VadOs1/jsource/"
          search-paths: "config-repo/auth-service"

eureka:
  instance:
    preferIpAddress: false

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/