server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VadOs1/jsource/
          searchPaths: config-repo/lead-service
logging:
  level:
    root: INFO